apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasbinder.fullname" . }}
  labels:
    app: {{ include "oasbinder.fullname" . }}
data:
  oasbinder.yaml: |
    {{- toYaml .Values.oasbinderConfig | nindent 4 }}
