apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasbinder.fullname" . }}
  labels:
    app: {{ include "oasbinder.fullname" . }}
data:
  {{- with .Values.oasbinderConfig }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
