# Default values for oasbinder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/insightsengineering/oasbinder
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# args:
#   - "--config"
#   - "/oasbinder.yaml"
#   - "--logLevel"
#   - "debug"

# volumeMounts:
#   - name: config-volume
#     mountPath: /oasbinder.yaml
#     subPath: oasbinder.yaml

# volumes:
#   - name: config-volume
#     configMap:
#       name: oasbinder

# securityContext:
#   readOnlyRootFilesystem: false
#   runAsNonRoot: true
#   runAsUser: 999
#   runAsGroup: 999

# oasbinderConfig:
#   proxyAddress: http://localhost:10001
#   listenPort: 8080
#   listenAddress: 0.0.0.0

#   services:
#     - endpoint: /hogwarts
#       url: http://localhost:8000/hogwarts/
#       swagger_url: http://localhost:8000/hogwarts/

#   headers:
#     api-key: qwerty
