name: Release 🎈

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

permissions: read-all

jobs:
  chart-releaser:
    name: Create Release 🥇
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names 🌿
        id: branch-name
        uses: tj-actions/branch-names@e497ceb8ccd43fd9573cf2e375216625bc411d1f # v9.0.0
        with:
          strip_tag_prefix: v

      - name: Checkout Repo 🛎
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set chart-releaser configuration ⚙️
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # Override the default chart-releaser release name.
          cat << EOF > chart-releaser-config.yaml
          release-name-template: "v{{ .Version }}"
          EOF
          yq e -i '.version = "${{ steps.branch-name.outputs.tag }}"' helm/templates/Chart.yaml
          yq e -i '.appVersion = "${{ steps.branch-name.outputs.tag }}"' helm/templates/Chart.yaml

      - name: Run chart-releaser ⛵
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          charts_dir: helm
          config: chart-releaser-config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # goreleaser runs in a separate job because it needs a clean git state.
  goreleaser:
    needs: chart-releaser
    name: Run goreleaser 🐹
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 🛎
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup Go 🐹
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.24.5
          cache: true
          cache-dependency-path: go.sum

      - name: Log in to the Container registry 🗝
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser 🚀
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


